### ISSUE TITLE
Auto add http:// if no url protocol is specified.

### ISSUE THREAD

**Issue by grant** [karan/s#6]
This protocol should be assumed to be `http` if not specified

Use case:
- Type `google.com` and press enter

**Comment by karan** [comment]
What if the user enters `This protocol should be assumed to be http if not specified`? Also, cannot make assumptions about the protocol.

**Comment by grant** [comment]
If a user enters that, then it shouldn't be considered a valid URL. Use http://goo.gl/ as an example of what is valid/invalid.

**Comment by karan** [comment]
![image](https://f.cloud.github.com/assets/3261985/2178316/6a943bfa-9663-11e3-8538-ba7f10590e22.png)

This can sometimes be a security concern, and not a great UX.
